#!/usr/bin/env python3
"""
review/scripts/save-reviews.py
Import reviewer comments from a JSON export (generated by the dashboard's
"Save to review/reviews.json" button) into review/reviews.json.

Once saved, run build_data.py to embed the synced reviews into data.json,
then refresh the dashboard to see synced reviews alongside local ones.

Usage:
    # From a file exported by the dashboard:
    python review/scripts/save-reviews.py path/to/reviews-export.json

    # Pipe from clipboard / another process:
    cat reviews-export.json | python review/scripts/save-reviews.py

    # Verify the current reviews file:
    python review/scripts/save-reviews.py --check

Note:
    - This script NEVER writes to action/ — only to review/.
    - The sync-from-action.py script handles action/ -> review/ copying.
      Those two directions are kept separate.
"""
import json
import os
import sys
from datetime import datetime

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
REVIEWS_PATH = os.path.join(REPO_ROOT, 'review', 'reviews.json')
REVIEWS_ARCHIVE_DIR = os.path.join(REPO_ROOT, 'review', 'archive', 'reviews')

# Schema version for forward compatibility
SCHEMA_VERSION = 1


def validate_reviews(data):
    """Check that the data structure matches the expected reviews format."""
    if not isinstance(data, dict):
        return False, 'Root must be a JSON object (artifact-id → reviews map).'
    for aid, reviews in data.items():
        if not isinstance(aid, str):
            return False, f'Artifact ID must be a string, got {type(aid).__name__}.'
        if not isinstance(reviews, list):
            return False, f'Reviews for "{aid}" must be an array.'
        for i, r in enumerate(reviews):
            if not isinstance(r, dict):
                return False, f'Review #{i} in "{aid}" must be an object.'
            for key in ('name', 'rating', 'text', 'timestamp'):
                if key not in r:
                    return False, f'Review #{i} in "{aid}" missing required field "{key}".'
    return True, 'OK'


def load_existing():
    """Load existing reviews.json, returning empty dict if not found."""
    if not os.path.exists(REVIEWS_PATH):
        return {}
    try:
        with open(REVIEWS_PATH, 'r', encoding='utf-8') as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError) as e:
        print(f'⚠️  Warning: could not read existing {REVIEWS_PATH}: {e}', file=sys.stderr)
        return {}


def merge_reviews(existing, incoming):
    """Merge incoming reviews into existing, preserving both."""
    merged = dict(existing)
    for aid, reviews in incoming.items():
        if aid not in merged:
            merged[aid] = []
        existing_ids = {r.get('id') for r in merged[aid]}
        for r in reviews:
            # Deduplicate by id field if present, otherwise by timestamp+name
            rid = r.get('id')
            if rid and rid in existing_ids:
                continue
            if not rid:
                dup = any(
                    er.get('name') == r.get('name')
                    and er.get('timestamp') == r.get('timestamp')
                    and er.get('text') == r.get('text')
                    for er in merged[aid]
                )
                if dup:
                    continue
            merged[aid].append(r)
    return merged


def main():
    # Parse flags
    do_archive = False
    args = [a for a in sys.argv[1:] if not a.startswith('--')]
    flags = [a for a in sys.argv[1:] if a.startswith('--')]

    for flag in flags:
        if flag == '--archive':
            do_archive = True
        elif flag == '--check':
            pass  # handled below
        else:
            print(f'❌ Unknown flag: {flag}', file=sys.stderr)
            print(f'   Usage: python {__file__} [--archive] [<file>]', file=sys.stderr)
            sys.exit(1)

    if '--check' in flags:
        # Verify mode: check if reviews.json is valid
        if not os.path.exists(REVIEWS_PATH):
            print(f'❌ {REVIEWS_PATH} not found. No reviews have been saved yet.')
            sys.exit(1)
        try:
            with open(REVIEWS_PATH, 'r', encoding='utf-8') as f:
                data = json.load(f)
            valid, msg = validate_reviews(data)
            if valid:
                total = sum(len(v) for v in data.values())
                print(f'✅ {REVIEWS_PATH} — {total} review(s) across {len(data)} artifact(s).')
            else:
                print(f'❌ Validation failed: {msg}')
                sys.exit(1)
        except (json.JSONDecodeError, OSError) as e:
            print(f'❌ Could not read {REVIEWS_PATH}: {e}')
            sys.exit(1)
        return

    # Read incoming data
    incoming = None
    src_path = args[0] if args else None
    if src_path:
        if not os.path.isfile(src_path):
            print(f'❌ File not found: {src_path}', file=sys.stderr)
            sys.exit(1)
        try:
            with open(src_path, 'r', encoding='utf-8') as f:
                incoming = json.load(f)
            print(f'📖 Read {os.path.basename(src_path)}')
        except (json.JSONDecodeError, OSError) as e:
            print(f'❌ Could not read {src_path}: {e}', file=sys.stderr)
            sys.exit(1)
    else:
        # Read from stdin (pipe)
        try:
            incoming = json.load(sys.stdin)
            print('📖 Read reviews from stdin', file=sys.stderr)
        except json.JSONDecodeError as e:
            print('❌ Could not parse JSON from stdin.', file=sys.stderr)
            print(f'   Usage: python {__file__} < reviews-export.json', file=sys.stderr)
            sys.exit(1)

    # Validate
    valid, msg = validate_reviews(incoming)
    if not valid:
        print(f'❌ Invalid reviews data: {msg}', file=sys.stderr)
        sys.exit(1)

    # Merge with existing
    existing = load_existing()
    merged = merge_reviews(existing, incoming)

    # Count
    new_count = sum(len(v) for v in incoming.values())
    existing_count = sum(len(v) for v in existing.values())
    merged_count = sum(len(v) for v in merged.values())

    # Archive previous reviews if --archive flag set
    if do_archive and os.path.exists(REVIEWS_PATH):
        os.makedirs(REVIEWS_ARCHIVE_DIR, exist_ok=True)
        timestamp = datetime.now().strftime('%Y-%m-%d_%H%M%S')
        archive_path = os.path.join(REVIEWS_ARCHIVE_DIR, f'{timestamp}.json')
        with open(REVIEWS_PATH, 'r', encoding='utf-8') as f:
            previous = json.load(f)
        with open(archive_path, 'w', encoding='utf-8') as f:
            json.dump(previous, f, indent=2, ensure_ascii=False)
        print(f'📦 Archived previous reviews to {archive_path}')

    # Write
    os.makedirs(os.path.dirname(REVIEWS_PATH), exist_ok=True)
    with open(REVIEWS_PATH, 'w', encoding='utf-8') as f:
        json.dump(merged, f, indent=2, ensure_ascii=False)

    print(f'✅ Saved to {REVIEWS_PATH}')
    print(f'   Existing: {existing_count} review(s) | Incoming: {new_count} review(s) | Total: {merged_count} review(s)')
    print(f'   Next: run "python action/dashboard/build_data.py" to embed in dashboard.')


if __name__ == '__main__':
    main()
